/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminPanelRouteImport } from './routes/_authenticated/admin-panel'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRatingRouteImport } from './routes/_authenticated/rating'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedWaterRouteImport } from './routes/_authenticated/water'
import { Route as AuthenticatedWorkerRouteImport } from './routes/_authenticated/worker'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LiteIndexRouteImport } from './routes/lite/index'
import { Route as LiteDepotsRouteImport } from './routes/lite/depots'
import { Route as LiteLoginRouteImport } from './routes/lite/login'
import { Route as LiteLogoutRouteImport } from './routes/lite/logout'
import { Route as LiteProfileRouteImport } from './routes/lite/profile'
import { Route as LiteRatingRouteImport } from './routes/lite/rating'
import { Route as LiteReportRouteImport } from './routes/lite/report'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPanelRoute = AuthenticatedAdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRatingRoute = AuthenticatedRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaterRoute = AuthenticatedWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerRoute = AuthenticatedWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteIndexRoute = LiteIndexRouteImport.update({
  id: '/lite/',
  path: '/lite/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteDepotsRoute = LiteDepotsRouteImport.update({
  id: '/lite/depots',
  path: '/lite/depots',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteLoginRoute = LiteLoginRouteImport.update({
  id: '/lite/login',
  path: '/lite/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteLogoutRoute = LiteLogoutRouteImport.update({
  id: '/lite/logout',
  path: '/lite/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteProfileRoute = LiteProfileRouteImport.update({
  id: '/lite/profile',
  path: '/lite/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteRatingRoute = LiteRatingRouteImport.update({
  id: '/lite/rating',
  path: '/lite/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteReportRoute = LiteReportRouteImport.update({
  id: '/lite/report',
  path: '/lite/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-panel': typeof AuthenticatedAdminPanelRoute
  '/chat': typeof AuthenticatedChatRoute
  '/map': typeof AuthenticatedMapRoute
  '/market': typeof AuthenticatedMarketRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rating': typeof AuthenticatedRatingRoute
  '/report': typeof AuthenticatedReportRoute
  '/water': typeof AuthenticatedWaterRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/lite/depots': typeof LiteDepotsRoute
  '/lite/login': typeof LiteLoginRoute
  '/lite/logout': typeof LiteLogoutRoute
  '/lite/profile': typeof LiteProfileRoute
  '/lite/rating': typeof LiteRatingRoute
  '/lite/report': typeof LiteReportRoute
  '/auth/': typeof AuthIndexRoute
  '/lite/': typeof LiteIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-panel': typeof AuthenticatedAdminPanelRoute
  '/chat': typeof AuthenticatedChatRoute
  '/map': typeof AuthenticatedMapRoute
  '/market': typeof AuthenticatedMarketRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/rating': typeof AuthenticatedRatingRoute
  '/report': typeof AuthenticatedReportRoute
  '/water': typeof AuthenticatedWaterRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/lite/depots': typeof LiteDepotsRoute
  '/lite/login': typeof LiteLoginRoute
  '/lite/logout': typeof LiteLogoutRoute
  '/lite/profile': typeof LiteProfileRoute
  '/lite/rating': typeof LiteRatingRoute
  '/lite/report': typeof LiteReportRoute
  '/auth': typeof AuthIndexRoute
  '/lite': typeof LiteIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin-panel': typeof AuthenticatedAdminPanelRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/rating': typeof AuthenticatedRatingRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/water': typeof AuthenticatedWaterRoute
  '/_authenticated/worker': typeof AuthenticatedWorkerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/lite/depots': typeof LiteDepotsRoute
  '/lite/login': typeof LiteLoginRoute
  '/lite/logout': typeof LiteLogoutRoute
  '/lite/profile': typeof LiteProfileRoute
  '/lite/rating': typeof LiteRatingRoute
  '/lite/report': typeof LiteReportRoute
  '/auth/': typeof AuthIndexRoute
  '/lite/': typeof LiteIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin-panel'
    | '/chat'
    | '/map'
    | '/market'
    | '/profile'
    | '/rating'
    | '/report'
    | '/water'
    | '/worker'
    | '/auth/callback'
    | '/lite/depots'
    | '/lite/login'
    | '/lite/logout'
    | '/lite/profile'
    | '/lite/rating'
    | '/lite/report'
    | '/auth/'
    | '/lite/'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin-panel'
    | '/chat'
    | '/map'
    | '/market'
    | '/profile'
    | '/rating'
    | '/report'
    | '/water'
    | '/worker'
    | '/auth/callback'
    | '/lite/depots'
    | '/lite/login'
    | '/lite/logout'
    | '/lite/profile'
    | '/lite/rating'
    | '/lite/report'
    | '/auth'
    | '/lite'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin-panel'
    | '/_authenticated/chat'
    | '/_authenticated/map'
    | '/_authenticated/market'
    | '/_authenticated/profile'
    | '/_authenticated/rating'
    | '/_authenticated/report'
    | '/_authenticated/water'
    | '/_authenticated/worker'
    | '/auth/callback'
    | '/lite/depots'
    | '/lite/login'
    | '/lite/logout'
    | '/lite/profile'
    | '/lite/rating'
    | '/lite/report'
    | '/auth/'
    | '/lite/'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  LiteDepotsRoute: typeof LiteDepotsRoute
  LiteLoginRoute: typeof LiteLoginRoute
  LiteLogoutRoute: typeof LiteLogoutRoute
  LiteProfileRoute: typeof LiteProfileRoute
  LiteRatingRoute: typeof LiteRatingRoute
  LiteReportRoute: typeof LiteReportRoute
  AuthIndexRoute: typeof AuthIndexRoute
  LiteIndexRoute: typeof LiteIndexRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-panel': {
      id: '/_authenticated/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AuthenticatedAdminPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rating': {
      id: '/_authenticated/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof AuthenticatedRatingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/water': {
      id: '/_authenticated/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof AuthenticatedWaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker': {
      id: '/_authenticated/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof AuthenticatedWorkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite/': {
      id: '/lite/'
      path: '/lite'
      fullPath: '/lite/'
      preLoaderRoute: typeof LiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite/depots': {
      id: '/lite/depots'
      path: '/lite/depots'
      fullPath: '/lite/depots'
      preLoaderRoute: typeof LiteDepotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite/login': {
      id: '/lite/login'
      path: '/lite/login'
      fullPath: '/lite/login'
      preLoaderRoute: typeof LiteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite/logout': {
      id: '/lite/logout'
      path: '/lite/logout'
      fullPath: '/lite/logout'
      preLoaderRoute: typeof LiteLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite/profile': {
      id: '/lite/profile'
      path: '/lite/profile'
      fullPath: '/lite/profile'
      preLoaderRoute: typeof LiteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite/rating': {
      id: '/lite/rating'
      path: '/lite/rating'
      fullPath: '/lite/rating'
      preLoaderRoute: typeof LiteRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lite/report': {
      id: '/lite/report'
      path: '/lite/report'
      fullPath: '/lite/report'
      preLoaderRoute: typeof LiteReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminPanelRoute: typeof AuthenticatedAdminPanelRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRatingRoute: typeof AuthenticatedRatingRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedWaterRoute: typeof AuthenticatedWaterRoute
  AuthenticatedWorkerRoute: typeof AuthenticatedWorkerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminPanelRoute: AuthenticatedAdminPanelRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRatingRoute: AuthenticatedRatingRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedWaterRoute: AuthenticatedWaterRoute,
  AuthenticatedWorkerRoute: AuthenticatedWorkerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  LiteDepotsRoute: LiteDepotsRoute,
  LiteLoginRoute: LiteLoginRoute,
  LiteLogoutRoute: LiteLogoutRoute,
  LiteProfileRoute: LiteProfileRoute,
  LiteRatingRoute: LiteRatingRoute,
  LiteReportRoute: LiteReportRoute,
  AuthIndexRoute: AuthIndexRoute,
  LiteIndexRoute: LiteIndexRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
